name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
      REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4 
    - name: connect to docker hub
      run:  echo REGISTRY_PASS | docker login --username REGISTRY_USER    --password-stdin 
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:v1
        docker push my-image-name:v1
